In [1]:
import warnings
warnings.simplefilter("ignore")

In [2]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.utils import to_categorical

In [6]:
datatrain = pd.read_csv('data/iris_train.csv')
datatrain.head(5)

sepal_length  sepal_width  pedal_length  pedal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.4           1.5          0.2  Iris-setosa

In [10]:
datatrain.loc[datatrain['class'] == 'Iris-setosa', 'class'] = 0
datatrain.loc[datatrain['class'] == 'Iris-versicolor','class'] = 1
datatrain.loc[datatrain['class'] == 'Iris-virginica', 'class'] = 2
datatrain = datatrain.apply(pd.to_numeric)

In [11]:
datatrain.head(5)

sepal_length  sepal_width  pedal_length  pedal_width  class
0           5.1          3.5           1.4          0.2      0
1           4.9          3.0           1.4          0.2      0
2           4.7          3.2           1.3          0.2      0
3           4.6          3.1           1.5          0.2      0
4           5.0          3.4           1.5          0.2      0

In [14]:
datatrain_array = datatrain.values
datatrain_array

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.6, 0.2, 0. ],
       [4.8, 3.1, 1.6, 0.2, 0. ],
       [5.4, 3.4, 1.5, 0.4, 0. ],
       [5.2, 4.1, 1.5, 0.1, 0. ],
       [5.5, 4.2, 1.4, 0.2, 0. ],
       [4.9, 3

In [15]:
x_train = datatrain_array[:,:4]
x_train

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3

In [19]:
y_train = datatrain_array[:,4]
y_train

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
#change target format
y_train = to_categorical(y_train)
y_train

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0

***Build a Sequential Keras Model***

Build a squential Keras model Multilayer perceptron model, with one hidden layer. Input layer : 4 neuron, represents the feature of Iris(Sepal Length etc) Hidden layer : 10 neuron, activation using ReLU Output layer : 3 neuron, represents the class of Iris, Softmax Layer

In [22]:
model = Sequential()
model.add(Dense(units=10, input_dim=4))
model.add(Activation("relu"))
model.add(Dense(units=3))
model.add(Activation("softmax"))

In [23]:
#Compile the model and choose an optimizer and loss function for training and optimizing your data.
#optimizer = stochastic gradient descent with no batch-size
#loss function = categorical cross entropy
#learning rate = default from keras.optimizer.SGD, 0.01
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

In [50]:
#Train the model using the datatrain‘model.fit’ function.
model.fit(x_train, y_train, epochs=100, batch_size=120)

Epoch 1/100
2/2 [==============================] - 0s 2ms/step - loss: 0.4746 - accuracy: 0.9185
Epoch 2/100
2/2 [==============================] - 0s 2ms/step - loss: 0.4698 - accuracy: 0.8148
Epoch 3/100
2/2 [==============================] - 0s 2ms/step - loss: 0.4842 - accuracy: 0.6667
Epoch 4/100
2/2 [==============================] - 0s 2ms/step - loss: 0.4720 - accuracy: 0.6963
Epoch 5/100
2/2 [==============================] - 0s 2ms/step - loss: 0.4700 - accuracy: 0.6963
Epoch 6/100
2/2 [==============================] - 0s 3ms/step - loss: 0.4631 - accuracy: 0.7704
Epoch 7/100
2/2 [==============================] - 0s 3ms/step - loss: 0.4601 - accuracy: 0.8296
Epoch 8/100
2/2 [==============================] - 0s 3ms/step - loss: 0.4573 - accuracy: 0.8667
Epoch 9/100
2/2 [==============================] - 0s 3ms/step - loss: 0.4552 - accuracy: 0.9259
Epoch 10/100
2/2 [==============================] - 0s 3ms/step - loss: 0.4543 - accuracy: 0.9333
Epoch 11/100
2/2 [===========

In [35]:
## Evaluate on test data
#load and Prepare Data
datatest = pd.read_csv('data/iris_test.csv')
datatest.head(5)

sepal_length  sepal_width  pedal_length  pedal_width        class
0           5.4          3.9           1.7          0.4  Iris-setosa
1           5.4          3.9           1.3          0.4  Iris-setosa
2           5.0          3.6           1.4          0.2  Iris-setosa
3           4.6          3.4           1.4          0.3  Iris-setosa
4           5.0          3.4           1.6          0.4  Iris-setosa

In [36]:
datatest.loc[datatest['class'] == 'Iris-setosa', 'class'] = 0
datatest.loc[datatest['class'] == 'Iris-versicolor','class'] = 1
datatest.loc[datatest['class'] == 'Iris-virginica', 'class'] = 2
datatest = datatest.apply(pd.to_numeric)

In [37]:
#change dataframe to array
datatest_array = datatest.values

In [38]:
#split x and y (feature and target)
x_test= datatest_array[:,:4]
y_test = datatest_array[:,4]

In [44]:
# Get predictions
predictions = model.predict(x_test, batch_size=120)
predictions

1/1 [==============================] - 0s 11ms/step


array([[0.8867737 , 0.08976829, 0.02345784],
       [0.92788446, 0.05700643, 0.01510904],
       [0.8921137 , 0.08668464, 0.02120165],
       [0.86440563, 0.10491169, 0.03068255],
       [0.834981  , 0.1254987 , 0.03952035],
       [0.0152964 , 0.45592272, 0.5287808 ],
       [0.01377683, 0.35911518, 0.6271079 ],
       [0.01938087, 0.40058196, 0.5800371 ],
       [0.04169598, 0.4370582 , 0.52124584],
       [0.01074594, 0.3539321 , 0.635322  ],
       [0.09346358, 0.4731694 , 0.43336698],
       [0.08459368, 0.5190711 , 0.39633524],
       [0.0632894 , 0.48880422, 0.44790637],
       [0.07457969, 0.5341288 , 0.39129156],
       [0.09203456, 0.51167166, 0.39629376]], dtype=float32)

In [45]:
predicted_classes = predictions.argmax(axis=-1)
predicted_classes

array([0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1])

In [43]:
# Convert ytest to numpy array if it's not already
ytest_np = np.array(ytest)

#get accuration
accuration = np.sum(predicted_classes == ytest_np)/len(ytest) * 100
accuration

100.0

In [46]:
#Printing the accuracy generated by the model
print("Test Accuration : " + str(accuration) + '%')
print("Prediction :")
print(classes)
print("Target :")
print(np.asarray(ytest,dtype="int32"))

Test Accuration : 100.0%
Prediction :
[[0.8867737  0.08976829 0.02345784]
 [0.92788446 0.05700643 0.01510904]
 [0.8921137  0.08668464 0.02120165]
 [0.86440563 0.10491169 0.03068255]
 [0.834981   0.1254987  0.03952035]
 [0.0152964  0.45592272 0.5287808 ]
 [0.01377683 0.35911518 0.6271079 ]
 [0.01938087 0.40058196 0.5800371 ]
 [0.04169598 0.4370582  0.52124584]
 [0.01074594 0.3539321  0.635322  ]
 [0.09346358 0.4731694  0.43336698]
 [0.08459368 0.5190711  0.39633524]
 [0.0632894  0.48880422 0.44790637]
 [0.07457969 0.5341288  0.39129156]
 [0.09203456 0.51167166 0.39629376]]
Target :
[0 0 0 0 0 2 2 2 2 2 1 1 1 1 1]
